CREATE TABLE IF NOT EXISTS users(
    chat_id INTEGER UNIQUE PRIMARY KEY NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT,
    time_created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS polls(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    content TEXT NOT NULL,
    time_created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS answers(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    poll_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    time_created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_poll FOREIGN KEY(poll_id) REFERENCES polls(id)
 );

CREATE TABLE IF NOT EXISTS votes(
    chat_id INTEGER NOT NULL,
    poll_id INTEGER NOT NULL,
    answer_id INTEGER NOT NULL,
    time_created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(chat_id, poll_id),
    CONSTRAINT fk_user FOREIGN KEY(chat_id) REFERENCES users(chat_id),
    CONSTRAINT fk_poll FOREIGN KEY(poll_id) REFERENCES polls(id),
    CONSTRAINT fk_answer FOREIGN KEY(answer_id) REFERENCES answers(id)
 );

